import { TTeamRankInfo } from '@/types/leagues';

export const rankInfo: TTeamRankInfo = {
  rankInfo: [
    {
      matchDay: 1,
      ranks: [
        {
          teamId: 319,
          teamName: 'Brighton & Hove Albion FC',
          season: '2024',
          rank: 1,
          won: 1,
          lost: 0,
          draw: 0,
          points: 3,
          goalsFor: 3,
          goalsAgainst: 0,
        },
        {
          teamId: 308,
          teamName: 'Liverpool FC',
          season: '2024',
          rank: 2,
          won: 1,
          lost: 0,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 0,
        },
        {
          teamId: 303,
          teamName: 'Arsenal FC',
          season: '2024',
          rank: 3,
          won: 1,
          lost: 0,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 0,
        },
        {
          teamId: 309,
          teamName: 'Manchester City FC',
          season: '2024',
          rank: 4,
          won: 1,
          lost: 0,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 0,
        },
        {
          teamId: 304,
          teamName: 'Aston Villa FC',
          season: '2024',
          rank: 5,
          won: 1,
          lost: 0,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 1,
        },
        {
          teamId: 320,
          teamName: 'Brentford FC',
          season: '2024',
          rank: 6,
          won: 1,
          lost: 0,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 1,
        },
        {
          teamId: 310,
          teamName: 'Manchester United FC',
          season: '2024',
          rank: 7,
          won: 1,
          lost: 0,
          draw: 0,
          points: 3,
          goalsFor: 1,
          goalsAgainst: 0,
        },
        {
          teamId: 311,
          teamName: 'Newcastle United FC',
          season: '2024',
          rank: 8,
          won: 1,
          lost: 0,
          draw: 0,
          points: 3,
          goalsFor: 1,
          goalsAgainst: 0,
        },
        {
          teamId: 317,
          teamName: 'Nottingham Forest FC',
          season: '2024',
          rank: 9,
          won: 0,
          lost: 0,
          draw: 1,
          points: 1,
          goalsFor: 1,
          goalsAgainst: 1,
        },
        {
          teamId: 322,
          teamName: 'AFC Bournemouth',
          season: '2024',
          rank: 10,
          won: 0,
          lost: 0,
          draw: 1,
          points: 1,
          goalsFor: 1,
          goalsAgainst: 1,
        },
        {
          teamId: 314,
          teamName: 'Leicester City FC',
          season: '2024',
          rank: 11,
          won: 0,
          lost: 0,
          draw: 1,
          points: 1,
          goalsFor: 1,
          goalsAgainst: 1,
        },
        {
          teamId: 312,
          teamName: 'Tottenham Hotspur FC',
          season: '2024',
          rank: 12,
          won: 0,
          lost: 0,
          draw: 1,
          points: 1,
          goalsFor: 1,
          goalsAgainst: 1,
        },
        {
          teamId: 321,
          teamName: 'West Ham United FC',
          season: '2024',
          rank: 13,
          won: 0,
          lost: 1,
          draw: 0,
          points: 0,
          goalsFor: 1,
          goalsAgainst: 2,
        },
        {
          teamId: 318,
          teamName: 'Crystal Palace FC',
          season: '2024',
          rank: 14,
          won: 0,
          lost: 1,
          draw: 0,
          points: 0,
          goalsFor: 1,
          goalsAgainst: 2,
        },
        {
          teamId: 307,
          teamName: 'Fulham FC',
          season: '2024',
          rank: 15,
          won: 0,
          lost: 1,
          draw: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 1,
        },
        {
          teamId: 315,
          teamName: 'Southampton FC',
          season: '2024',
          rank: 16,
          won: 0,
          lost: 1,
          draw: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 1,
        },
        {
          teamId: 316,
          teamName: 'Ipswich Town FC',
          season: '2024',
          rank: 17,
          won: 0,
          lost: 1,
          draw: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 2,
        },
        {
          teamId: 313,
          teamName: 'Wolverhampton Wanderers FC',
          season: '2024',
          rank: 18,
          won: 0,
          lost: 1,
          draw: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 2,
        },
        {
          teamId: 305,
          teamName: 'Chelsea FC',
          season: '2024',
          rank: 19,
          won: 0,
          lost: 1,
          draw: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 2,
        },
        {
          teamId: 306,
          teamName: 'Everton FC',
          season: '2024',
          rank: 20,
          won: 0,
          lost: 1,
          draw: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 3,
        },
      ],
    },
    {
      matchDay: 2,
      ranks: [
        {
          teamId: 309,
          teamName: 'Manchester City FC',
          season: '2024',
          rank: 1,
          won: 2,
          lost: 0,
          draw: 0,
          points: 6,
          goalsFor: 6,
          goalsAgainst: 1,
        },
        {
          teamId: 319,
          teamName: 'Brighton & Hove Albion FC',
          season: '2024',
          rank: 2,
          won: 2,
          lost: 0,
          draw: 0,
          points: 6,
          goalsFor: 5,
          goalsAgainst: 1,
        },
        {
          teamId: 308,
          teamName: 'Liverpool FC',
          season: '2024',
          rank: 3,
          won: 2,
          lost: 0,
          draw: 0,
          points: 6,
          goalsFor: 4,
          goalsAgainst: 0,
        },
        {
          teamId: 303,
          teamName: 'Arsenal FC',
          season: '2024',
          rank: 4,
          won: 2,
          lost: 0,
          draw: 0,
          points: 6,
          goalsFor: 4,
          goalsAgainst: 0,
        },
        {
          teamId: 312,
          teamName: 'Tottenham Hotspur FC',
          season: '2024',
          rank: 5,
          won: 1,
          lost: 0,
          draw: 1,
          points: 4,
          goalsFor: 5,
          goalsAgainst: 1,
        },
        {
          teamId: 311,
          teamName: 'Newcastle United FC',
          season: '2024',
          rank: 6,
          won: 1,
          lost: 0,
          draw: 1,
          points: 4,
          goalsFor: 2,
          goalsAgainst: 1,
        },
        {
          teamId: 317,
          teamName: 'Nottingham Forest FC',
          season: '2024',
          rank: 7,
          won: 1,
          lost: 0,
          draw: 1,
          points: 4,
          goalsFor: 2,
          goalsAgainst: 1,
        },
        {
          teamId: 305,
          teamName: 'Chelsea FC',
          season: '2024',
          rank: 8,
          won: 1,
          lost: 1,
          draw: 0,
          points: 3,
          goalsFor: 6,
          goalsAgainst: 4,
        },
        {
          teamId: 321,
          teamName: 'West Ham United FC',
          season: '2024',
          rank: 9,
          won: 1,
          lost: 1,
          draw: 0,
          points: 3,
          goalsFor: 3,
          goalsAgainst: 2,
        },
        {
          teamId: 310,
          teamName: 'Manchester United FC',
          season: '2024',
          rank: 10,
          won: 1,
          lost: 1,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 2,
        },
        {
          teamId: 307,
          teamName: 'Fulham FC',
          season: '2024',
          rank: 11,
          won: 1,
          lost: 1,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 2,
        },
        {
          teamId: 304,
          teamName: 'Aston Villa FC',
          season: '2024',
          rank: 12,
          won: 1,
          lost: 1,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 3,
        },
        {
          teamId: 320,
          teamName: 'Brentford FC',
          season: '2024',
          rank: 13,
          won: 1,
          lost: 1,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 3,
        },
        {
          teamId: 322,
          teamName: 'AFC Bournemouth',
          season: '2024',
          rank: 14,
          won: 0,
          lost: 0,
          draw: 2,
          points: 2,
          goalsFor: 2,
          goalsAgainst: 2,
        },
        {
          teamId: 314,
          teamName: 'Leicester City FC',
          season: '2024',
          rank: 15,
          won: 0,
          lost: 1,
          draw: 1,
          points: 1,
          goalsFor: 2,
          goalsAgainst: 3,
        },
        {
          teamId: 315,
          teamName: 'Southampton FC',
          season: '2024',
          rank: 16,
          won: 0,
          lost: 2,
          draw: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 2,
        },
        {
          teamId: 318,
          teamName: 'Crystal Palace FC',
          season: '2024',
          rank: 17,
          won: 0,
          lost: 2,
          draw: 0,
          points: 0,
          goalsFor: 1,
          goalsAgainst: 4,
        },
        {
          teamId: 316,
          teamName: 'Ipswich Town FC',
          season: '2024',
          rank: 18,
          won: 0,
          lost: 2,
          draw: 0,
          points: 0,
          goalsFor: 1,
          goalsAgainst: 6,
        },
        {
          teamId: 313,
          teamName: 'Wolverhampton Wanderers FC',
          season: '2024',
          rank: 19,
          won: 0,
          lost: 2,
          draw: 0,
          points: 0,
          goalsFor: 2,
          goalsAgainst: 8,
        },
        {
          teamId: 306,
          teamName: 'Everton FC',
          season: '2024',
          rank: 20,
          won: 0,
          lost: 2,
          draw: 0,
          points: 0,
          goalsFor: 0,
          goalsAgainst: 7,
        },
      ],
    },
    {
      matchDay: 3,
      ranks: [
        {
          teamId: 309,
          teamName: 'Manchester City FC',
          season: '2024',
          rank: 1,
          won: 3,
          lost: 0,
          draw: 0,
          points: 9,
          goalsFor: 9,
          goalsAgainst: 2,
        },
        {
          teamId: 308,
          teamName: 'Liverpool FC',
          season: '2024',
          rank: 2,
          won: 3,
          lost: 0,
          draw: 0,
          points: 9,
          goalsFor: 7,
          goalsAgainst: 0,
        },
        {
          teamId: 319,
          teamName: 'Brighton & Hove Albion FC',
          season: '2024',
          rank: 3,
          won: 2,
          lost: 0,
          draw: 1,
          points: 7,
          goalsFor: 6,
          goalsAgainst: 2,
        },
        {
          teamId: 303,
          teamName: 'Arsenal FC',
          season: '2024',
          rank: 4,
          won: 2,
          lost: 0,
          draw: 1,
          points: 7,
          goalsFor: 5,
          goalsAgainst: 1,
        },
        {
          teamId: 311,
          teamName: 'Newcastle United FC',
          season: '2024',
          rank: 5,
          won: 2,
          lost: 0,
          draw: 1,
          points: 7,
          goalsFor: 4,
          goalsAgainst: 2,
        },
        {
          teamId: 320,
          teamName: 'Brentford FC',
          season: '2024',
          rank: 6,
          won: 2,
          lost: 1,
          draw: 0,
          points: 6,
          goalsFor: 5,
          goalsAgainst: 4,
        },
        {
          teamId: 304,
          teamName: 'Aston Villa FC',
          season: '2024',
          rank: 7,
          won: 2,
          lost: 1,
          draw: 0,
          points: 6,
          goalsFor: 4,
          goalsAgainst: 4,
        },
        {
          teamId: 322,
          teamName: 'AFC Bournemouth',
          season: '2024',
          rank: 8,
          won: 1,
          lost: 0,
          draw: 2,
          points: 5,
          goalsFor: 5,
          goalsAgainst: 4,
        },
        {
          teamId: 317,
          teamName: 'Nottingham Forest FC',
          season: '2024',
          rank: 9,
          won: 1,
          lost: 0,
          draw: 2,
          points: 5,
          goalsFor: 3,
          goalsAgainst: 2,
        },
        {
          teamId: 312,
          teamName: 'Tottenham Hotspur FC',
          season: '2024',
          rank: 10,
          won: 1,
          lost: 1,
          draw: 1,
          points: 4,
          goalsFor: 6,
          goalsAgainst: 3,
        },
        {
          teamId: 305,
          teamName: 'Chelsea FC',
          season: '2024',
          rank: 11,
          won: 1,
          lost: 1,
          draw: 1,
          points: 4,
          goalsFor: 7,
          goalsAgainst: 5,
        },
        {
          teamId: 307,
          teamName: 'Fulham FC',
          season: '2024',
          rank: 12,
          won: 1,
          lost: 1,
          draw: 1,
          points: 4,
          goalsFor: 3,
          goalsAgainst: 3,
        },
        {
          teamId: 321,
          teamName: 'West Ham United FC',
          season: '2024',
          rank: 13,
          won: 1,
          lost: 2,
          draw: 0,
          points: 3,
          goalsFor: 4,
          goalsAgainst: 5,
        },
        {
          teamId: 310,
          teamName: 'Manchester United FC',
          season: '2024',
          rank: 14,
          won: 1,
          lost: 2,
          draw: 0,
          points: 3,
          goalsFor: 2,
          goalsAgainst: 5,
        },
        {
          teamId: 314,
          teamName: 'Leicester City FC',
          season: '2024',
          rank: 15,
          won: 0,
          lost: 2,
          draw: 1,
          points: 1,
          goalsFor: 3,
          goalsAgainst: 5,
        },
        {
          teamId: 318,
          teamName: 'Crystal Palace FC',
          season: '2024',
          rank: 16,
          won: 0,
          lost: 2,
          draw: 1,
          points: 1,
          goalsFor: 2,
          goalsAgainst: 5,
        },
        {
          teamId: 316,
          teamName: 'Ipswich Town FC',
          season: '2024',
          rank: 17,
          won: 0,
          lost: 2,
          draw: 1,
          points: 1,
          goalsFor: 2,
          goalsAgainst: 7,
        },
        {
          teamId: 313,
          teamName: 'Wolverhampton Wanderers FC',
          season: '2024',
          rank: 18,
          won: 0,
          lost: 2,
          draw: 1,
          points: 1,
          goalsFor: 3,
          goalsAgainst: 9,
        },
        {
          teamId: 315,
          teamName: 'Southampton FC',
          season: '2024',
          rank: 19,
          won: 0,
          lost: 3,
          draw: 0,
          points: 0,
          goalsFor: 1,
          goalsAgainst: 5,
        },
        {
          teamId: 306,
          teamName: 'Everton FC',
          season: '2024',
          rank: 20,
          won: 0,
          lost: 3,
          draw: 0,
          points: 0,
          goalsFor: 2,
          goalsAgainst: 10,
        },
      ],
    },
    {
      matchDay: 4,
      ranks: [
        {
          teamId: 309,
          teamName: 'Manchester City FC',
          season: '2024',
          rank: 1,
          won: 4,
          lost: 0,
          draw: 0,
          points: 12,
          goalsFor: 11,
          goalsAgainst: 3,
        },
        {
          teamId: 303,
          teamName: 'Arsenal FC',
          season: '2024',
          rank: 2,
          won: 3,
          lost: 0,
          draw: 1,
          points: 10,
          goalsFor: 6,
          goalsAgainst: 1,
        },
        {
          teamId: 311,
          teamName: 'Newcastle United FC',
          season: '2024',
          rank: 3,
          won: 3,
          lost: 0,
          draw: 1,
          points: 10,
          goalsFor: 6,
          goalsAgainst: 3,
        },
        {
          teamId: 308,
          teamName: 'Liverpool FC',
          season: '2024',
          rank: 4,
          won: 3,
          lost: 1,
          draw: 0,
          points: 9,
          goalsFor: 7,
          goalsAgainst: 1,
        },
        {
          teamId: 304,
          teamName: 'Aston Villa FC',
          season: '2024',
          rank: 5,
          won: 3,
          lost: 1,
          draw: 0,
          points: 9,
          goalsFor: 7,
          goalsAgainst: 6,
        },
        {
          teamId: 319,
          teamName: 'Brighton & Hove Albion FC',
          season: '2024',
          rank: 6,
          won: 2,
          lost: 0,
          draw: 2,
          points: 8,
          goalsFor: 6,
          goalsAgainst: 2,
        },
        {
          teamId: 317,
          teamName: 'Nottingham Forest FC',
          season: '2024',
          rank: 7,
          won: 2,
          lost: 0,
          draw: 2,
          points: 8,
          goalsFor: 4,
          goalsAgainst: 2,
        },
        {
          teamId: 305,
          teamName: 'Chelsea FC',
          season: '2024',
          rank: 8,
          won: 2,
          lost: 1,
          draw: 1,
          points: 7,
          goalsFor: 8,
          goalsAgainst: 5,
        },
        {
          teamId: 320,
          teamName: 'Brentford FC',
          season: '2024',
          rank: 9,
          won: 2,
          lost: 2,
          draw: 0,
          points: 6,
          goalsFor: 6,
          goalsAgainst: 6,
        },
        {
          teamId: 310,
          teamName: 'Manchester United FC',
          season: '2024',
          rank: 10,
          won: 2,
          lost: 2,
          draw: 0,
          points: 6,
          goalsFor: 5,
          goalsAgainst: 5,
        },
        {
          teamId: 322,
          teamName: 'AFC Bournemouth',
          season: '2024',
          rank: 11,
          won: 1,
          lost: 1,
          draw: 2,
          points: 5,
          goalsFor: 5,
          goalsAgainst: 5,
        },
        {
          teamId: 307,
          teamName: 'Fulham FC',
          season: '2024',
          rank: 12,
          won: 1,
          lost: 1,
          draw: 2,
          points: 5,
          goalsFor: 4,
          goalsAgainst: 4,
        },
        {
          teamId: 312,
          teamName: 'Tottenham Hotspur FC',
          season: '2024',
          rank: 13,
          won: 1,
          lost: 2,
          draw: 1,
          points: 4,
          goalsFor: 6,
          goalsAgainst: 4,
        },
        {
          teamId: 321,
          teamName: 'West Ham United FC',
          season: '2024',
          rank: 14,
          won: 1,
          lost: 2,
          draw: 1,
          points: 4,
          goalsFor: 5,
          goalsAgainst: 6,
        },
        {
          teamId: 314,
          teamName: 'Leicester City FC',
          season: '2024',
          rank: 15,
          won: 0,
          lost: 2,
          draw: 2,
          points: 2,
          goalsFor: 5,
          goalsAgainst: 7,
        },
        {
          teamId: 318,
          teamName: 'Crystal Palace FC',
          season: '2024',
          rank: 16,
          won: 0,
          lost: 2,
          draw: 2,
          points: 2,
          goalsFor: 4,
          goalsAgainst: 7,
        },
        {
          teamId: 316,
          teamName: 'Ipswich Town FC',
          season: '2024',
          rank: 17,
          won: 0,
          lost: 2,
          draw: 2,
          points: 2,
          goalsFor: 2,
          goalsAgainst: 7,
        },
        {
          teamId: 313,
          teamName: 'Wolverhampton Wanderers FC',
          season: '2024',
          rank: 18,
          won: 0,
          lost: 3,
          draw: 1,
          points: 1,
          goalsFor: 4,
          goalsAgainst: 11,
        },
        {
          teamId: 315,
          teamName: 'Southampton FC',
          season: '2024',
          rank: 19,
          won: 0,
          lost: 4,
          draw: 0,
          points: 0,
          goalsFor: 1,
          goalsAgainst: 8,
        },
        {
          teamId: 306,
          teamName: 'Everton FC',
          season: '2024',
          rank: 20,
          won: 0,
          lost: 4,
          draw: 0,
          points: 0,
          goalsFor: 4,
          goalsAgainst: 13,
        },
      ],
    },
  ],
};
